spring:
  profiles:
    active: dev
  application:
    name: businessdomain-transactions

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:9100/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"