server:
  port: 8080

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka